#! /bin/bash

echo "[Nagios]: Refreshing configuration." | /usr/local/sbin/irccat

/usr/local/sbin/print_xeriom_nagios_configuration > ~/xeriom_nagios.tmp

NEW_MD5=`md5sum ~/xeriom_nagios.tmp |cut -f 1 -d ' '`
OLD_MD5=`md5sum /etc/nagios2/conf.d/xeriom.cfg |cut -f 1 -d ' '`

if [ "x${OLD_MD5}" != "x${NEW_MD5}" ]; then
  echo "[Nagios]: Configuration changed, restarting." | /usr/local/sbin/irccat
  mv ~/xeriom_nagios.tmp /etc/nagios2/conf.d/xeriom.cfg
  /etc/init.d/nagios3 stop
  sleep 3
  /etc/init.d/nagios3 start
  if [ "0" = "$?" ]; then
    echo "[Nagios]: Restarted. http://monitor.xeriom.net/nagios" | /usr/local/sbin/irccat
  else
    echo "[Nagios]: Failed to restart, investigation required." | /usr/local/sbin/irccat
  fi
else
  echo "[Nagios]: Configuration unchanged." | /usr/local/sbin/irccat
  rm ~/xeriom_nagios.tmp
fi