#! /bin/bash

VM_NAME=$1
XM="/usr/sbin/xm"

xen_vm_stop $VM_NAME
if [ $? != "0" ]; then
  echo "Could not halt $VM_NAME. Bailing."
  exit 2
fi

if [ -d /var/vm ]; then
  VM_DEVICE_DIR="/var/vm/store"
  VM=`echo $VM_NAME |sed 's/\.vm\.xeriom\.net//'`
  VM_DEVICE="${VM_DEVICE_DIR}/$VM.img"
  MOUNT_OPTIONS="-o loop"
else
  VM_DEVICE_DIR="/dev/`hostname |cut -f 1 -d .`"
  VM=$VM_NAME
  VM_DEVICE="${VM_DEVICE_DIR}/$VM-disk"
  MOUNT_OPTIONS=""
fi

TMPDIR=`mktemp -d`
if [ ! -d $TMPDIR ]; then
  echo "Could not generate temporary directory $TMPDIR. Bailing."
  exit 2
fi

mount $MOUNT_OPTIONS $VM_DEVICE $TMPDIR 2>/dev/null
if [ $? -ne 0 ]; then
  echo "Could not mount $VM_DEVICE. Bailing."
  exit 2
fi

PASSWORD=`dd if=/dev/random count=20 bs=1 2>/dev/null | hexdump  | cut -d \  -f 2-| head -n 1 | tr -d " "`
chroot $TMPDIR sh -c "echo 'root:$PASSWORD' | chpasswd 2>/dev/null"
if [ $? != "0" ]; then
  echo "Could not set password. Bailing."
  exit 2
fi

umount $TMPDIR
if [ $? != "0" ]; then
  echo "Could not unmount VM from $TMPDIR. Bailing."
  exit 2
fi

mount |grep $TMPDIR
if [ $? = "0" ]; then
  echo "$TMPDIR is still mounted. Bailing."
  exit 2
fi

rm -rf $TMPDIR

xen_vm_stop $VM_NAME
if [ $? != "0" ]; then
  echo "Could not halt $VM_NAME. Bailing."
  exit 2
fi

xen_vm_start $VM_NAME

echo "$VM_NAME password changed to $PASSWORD"